version: "3.4"

services:
  mysql:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
